server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:memDb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: false
      open-in-view: fals

  sql:
    init:
      mode: always
      platform: h2
      continue-on-error: false
      data-locations:
        - classpath*:db/data-h2.sql
      schema-locations:
        - classpath*:db/schema-h2.sql
      encoding: UTF-8